- hosts: localhost
  become: yes

  tasks:
    - name: Build my App1
      shell: cd /home/andriamahefa/Desktop/DevOpsProject/DevOpsProject/App1 && docker build -t pythonapp:0.1 .
      tags:
        - python
        - build

    - name: Build my App2
      shell: cd /home/andriamahefa/Desktop/DevOpsProject/DevOpsProject/App2 && docker build -t pythonapp2:0.1 .
      tags:
        - python
        - build

    - name: Run ES container
      shell: cd /home/andriamahefa/Desktop/DevOpsProject/DevOpsProject/ElasticSearch && docker-compose up
      tags:
        - es

    - name: Run MySQL container
      shell: docker run --detach --name=mysql --env="MYSQL_ROOT_PASSWORD=admin" --publish 6603:3306 --volume=/root/docker/mysql/conf.d:/etc/mysql/conf.d mysql
      tags: run


#    - name: Run ES container
#      - shell: docker run -e ES_JAVA_OPTS="-Xms500m -Xmx500m" --name es01 --net elastic -p 9200:9200 -p 9300:9300 -it docker.elastic.co/elasticsearch/elasticsearch:8.3.1


    - name: Run App1 container
      shell: docker run -d -p 5001:5000 --name App1  pythonapp:0.1
      tags:
          - run

    - name: Run App2 container
      shell: docker run -d -p 5002:5000 --name App2  pythonapp2:0.1
      tags:
          - run


    - name: check
      uri:
        url: http://localhost:5001/
        method: GET
        status_code: 200
      tags:
        - check