from flask import Flask
from datetime import datetime
from elasticsearch import Elasticsearch, helpers
import requests

app = Flask(__name__)


@app.route('/')
def hello_world() :
    # Password for the 'elastic' user generated by Elasticsearch
    ELASTIC_PASSWORD = "7GDA-B_TwAJv8y_+EyeL"

    # Create the client instance
    client = Elasticsearch(
        "https://elastic:7GDA-B_TwAJv8y_+EyeL@localhost:9200",
        ca_certs="http_ca.crt",
        basic_auth=("elastic", ELASTIC_PASSWORD)
    )

    # Successful response!
    print(client.info())
    return 'Hello World!'


def

@app.post('/load')
def dataFromSQLtoES:
    data = requests.get("localhost:")



if __name__ == '__main__' :
    app.run()


sudo apt-get install docker-ce=5:20.10.17~3-0~ubuntu-jammy docker-ce-cli=5:20.10.17~3-0~ubuntu-jammy containerd.io docker-compose-plugin